[package]
name = "ascents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
rusqlite = "0.30.0"
time = { version = "0.3.30", features = ["macros", "parsing", "formatting"] }
